// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package authors

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db *sql.DB) *Queries {
	return &Queries{
		db: db,
	}
}

type Queries struct {
	db *sql.DB
	tx *sql.Tx
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: q.db,
		tx: tx,
	}
}
